### ISSUE TITLE
assumes seed unless .xml input file?

### ISSUE THREAD

**Issue by crotwell** [iris-edu/stationxml-validator#95]
This seems to work fine:
```
java -jar stationxml-validator-1.6.0.2-SNAPSHOT.jar  testdata/CO_JSC.xml --string
PASSED
```

But if I 
```
cp testdata/CO_JSC.xml testdata/CO_JSC.staxml

java -jar stationxml-validator-1.6.0.2-SNAPSHOT.jar  testdata/CO_JSC.staxml --string
java.lang.RuntimeException: java.io.IOException: Error calculation record length!
	at edu.iris.dmc.seed.blockette.util.BlocketteItrator.hasNext(BlocketteItrator.java:58)
	at edu.iris.dmc.IrisUtil.readSeed(IrisUtil.java:62)
	at edu.iris.dmc.IrisUtil.readSeed(IrisUtil.java:54)
	at edu.iris.dmc.Application.read(Application.java:158)
	at edu.iris.dmc.Application.run(Application.java:130)
	at edu.iris.dmc.Application.run(Application.java:121)
	at edu.iris.dmc.Application.main(Application.java:92)
Caused by: java.io.IOException: Error calculation record length!
	at edu.iris.dmc.seed.io.RecordInputStream.getRecordLength(RecordInputStream.java:99)
	at edu.iris.dmc.seed.io.RecordInputStream.next(RecordInputStream.java:32)
	at edu.iris.dmc.seed.blockette.util.BlocketteItrator.hasNext(BlocketteItrator.java:45)
	... 6 more
```

Same file, but it appears that if the file doesn't end in `.xml` it reads it as SEED. Seems weird that the default would be to read dataless within a stationxml validator???

If there are more than one type of input file allowed, it would be nice to have a cmd line arg to say what it is, maybe `--staxml` and --'seed' like:
```
java -jar stationxml-validator-1.6.0.2-SNAPSHOT.jar  --staxml testdata/CO_JSC.staxml --string
```

Guessing file types based off of file extensions is kind of dangerous and forcing naming as `.xml` is too restrictive.

**Comment by timronan** [comment]
This issue has been addressed by rule validator version stationxml-validator-1.7.0-RC-01. Please download this jar on the projects release page and verify that this function works satisfactorily. Report or close this issue based on your findings. 

Refer to commit: 26da0172591feab0814df9f4056ff470a11eb45c

**Comment by crotwell** [comment]
seems to work ok, closing
